### ISSUE TITLE
Gem from rubygems doesn't have instruction installments

### ISSUE THREAD

**Issue by zangrandi** [Irio/mymoip#27]
I was having an issue with installments not being generated to xml when my gemfile was like his:
    gem 'mymoip'

Then I added the git link and the installments were added correctly:
    gem 'mymoip', :git => 'git://github.com/Irio/mymoip.git

I do not understand how rubygems and gem versioning work but I think the version from rubygems were not updated since last commit.

**Comment by Irio** [comment]
Hi @zangrandi, this problem was caused because the code available in this repository wasn't released yet under a proper gem version. Case already solved with `0.6.0`.

With your line in the Gemfile you overwrote the RubyGems specification of latest stable version `0.5.0`, having access to the installments feature not yet released.

You can change your Gemfile to `gem 'mymoip'` again now and run `bundle update mymoip`.
